### ISSUE TITLE
Put some kind of auto-deployment script on the server

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/website#2]
At the moment deployment happens by my manually logging in and running `git pull` on the clone of the repo in the Nginx root.

It would be much better to have something (cronjob?) automatically detect changes, then rebuild the docs.

**Comment by justinclift** [comment]
Just added a super simple crontab line, that runs every minute and does a `git pull` in the website repo's root.  In theory, it should do the job. :smile:

**Comment by scottfurry** [comment]
> Just added a super simple crontab line, that runs every minute and does a `git pull` in the website repo's root. In theory, it should do the job.

You want to hit the git server every minute? Maybe every 15min or more. My $0.02.

**Comment by justinclift** [comment]
Good point.  Changed it to 10 minutes, as I get bored easily when waiting for things and 15 minutes is F O R E V E [oh look, a squirrel]...

**Comment by justinclift** [comment]
This simple cronjob approach seems to be working ok, as it automatically picked up the 1 liner change I made a few minutes ago.  No manual updating required any more.  Yay! :smile:
